Repository terraform-aws-modules/terraform-aws-eks, pull requests merged in 2021-05, with the labels that each got.

#1297 feat: Remove dependency on deprecated `hashicorp/template` provider
  data.tf
  examples/basic/versions.tf
  examples/fargate/versions.tf
  examples/irsa/versions.tf
  examples/launch_templates/versions.tf
  examples/launch_templates_with_managed_node_groups/versions.tf
  examples/managed_node_groups/versions.tf
  examples/secrets_encryption/versions.tf
  examples/spot_instances/versions.tf
  local.tf
  outputs.tf
  versions.tf
  workers.tf
  workers_launch_template.tf
Labels: breaking change

#1360 feat: Drop `asg_recreate_on_change` feature to encourage the usage of Instance Refresh for EC2 Auto Scaling
  local.tf
  workers.tf
  workers_launch_template.tf
Labels: breaking change, on hold

#1114 feat: Kubeconfig file should not be world or group readable by default
  README.md
  kubectl.tf
  variables.tf
Labels: breaking change

#1399 feat: Rename `config_output_path` into `kubeconfig_output_path` for naming consistency
  README.md
  kubectl.tf
  variables.tf
Labels: breaking change

#1378 feat: Add multiple selectors on the creation of Fargate profile
  examples/fargate/main.tf
  modules/fargate/README.md
  modules/fargate/fargate.tf
Labels: breaking change

#1372 feat: Drop random pets from Managed Node Groups
  README.md
  aws_auth.tf
  data.tf
  docs/upgrades.md
  examples/managed_node_groups/main.tf
  modules/fargate/README.md
  modules/fargate/versions.tf
  modules/node_groups/README.md
  modules/node_groups/launch_template.tf
  modules/node_groups/locals.tf
  modules/node_groups/node_groups.tf
  modules/node_groups/random.tf
  modules/node_groups/versions.tf
  versions.tf
Labels: breaking change, help wanted, needs_testing

#1274 feat: Add ability to use security groups for private access
  README.md
  cluster.tf
  variables.tf
Labels: breaking change
