Repository terraform-aws-modules/terraform-aws-eks, pull requests merged in 2021-09, with the labels that each got.

#1445 feat: Added throughput support for root and EBS disks
  README.md
  examples/launch_templates/main.tf
  local.tf
  versions.tf
  workers.tf
Labels: enhancement

#1082 fix: Put KubeletExtraArgs in double quotes for Windows
  templates/userdata_windows.tpl
Labels: needs update

#1560 feat: Supporting update_config in EKS managed node groups
  examples/managed_node_groups/main.tf
  modules/node_groups/README.md
  modules/node_groups/node_groups.tf
Labels: enhancement

#1563 feat: Add ability to tag network-interface using Launch Template
  examples/launch_templates_with_managed_node_groups/launchtemplate.tf
  modules/node_groups/launch_template.tf
  workers_launch_template.tf
Labels: enhancement

#1549 feat: Create SG rule for each new cluster_endpoint_private_access_cidr block
  cluster.tf
Labels: breaking change

#1473 feat: Added custom AMI support for managed node groups
  modules/node_groups/README.md
  modules/node_groups/launch_template.tf
  modules/node_groups/templates/userdata.sh.tpl
Labels: enhancement, help wanted
